apiVersion: v1
kind: ConfigMap
metadata:
  name: job-board-config
  namespace: app
data:
  GIN_MODE: "release"
  POSTGRES_HOST: "postgres-service"  # This will be our PostgreSQL service name
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "jobboard"
  POSTGRES_USER: "jobboard"
