apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-board-app
  namespace: app
  labels:
    app: job-board
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: job-board
  template:
    metadata:
      labels:
        app: job-board
    spec:
      containers:
      - name: job-board
        image: job-board:v1.0.0
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 8080
          name: http
        env:
        # From ConfigMap
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: job-board-config
              key: GIN_MODE
        # From Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: job-board-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
