# Development environment values

replicaCount: 1

image:
  tag: v1.0.2

service:
  type: NodePort
  port: 8080
  nodePort: 30081

config:
  ginMode: debug # Dev uses debug mode
  postgresDb: jobboard_dev
  postgresUser: jobboard

postgres:
  image:
    tag: 15-alpine
  storage: 256Mi
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 100m

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 200m
